uploads = []
outputs = []

[[generated]]
id = "rIimfhL9gevrh7LCsyffH"
uri = "file://assets/app-icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NuL6bcNVv5WVyEM_Y59-4"
uri = "file://assets/splash.png"
type = "image"
title = "generated_image"
